// Generated by gencpp from file bebop_simple_test/Altitude.msg
// DO NOT EDIT!


#ifndef BEBOP_SIMPLE_TEST_MESSAGE_ALTITUDE_H
#define BEBOP_SIMPLE_TEST_MESSAGE_ALTITUDE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bebop_simple_test
{
template <class ContainerAllocator>
struct Altitude_
{
  typedef Altitude_<ContainerAllocator> Type;

  Altitude_()
    : header()
    , altitude(0.0)  {
    }
  Altitude_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _altitude_type;
  _altitude_type altitude;




  typedef boost::shared_ptr< ::bebop_simple_test::Altitude_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bebop_simple_test::Altitude_<ContainerAllocator> const> ConstPtr;

}; // struct Altitude_

typedef ::bebop_simple_test::Altitude_<std::allocator<void> > Altitude;

typedef boost::shared_ptr< ::bebop_simple_test::Altitude > AltitudePtr;
typedef boost::shared_ptr< ::bebop_simple_test::Altitude const> AltitudeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bebop_simple_test::Altitude_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bebop_simple_test::Altitude_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bebop_simple_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'bebop_simple_test': ['/home/totonzx/catkin_pruebas/src/bebop_simple_test/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bebop_simple_test::Altitude_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bebop_simple_test::Altitude_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bebop_simple_test::Altitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bebop_simple_test::Altitude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bebop_simple_test::Altitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bebop_simple_test::Altitude_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bebop_simple_test::Altitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5073f650d09c8192d358641b48a0204b";
  }

  static const char* value(const ::bebop_simple_test::Altitude_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5073f650d09c8192ULL;
  static const uint64_t static_value2 = 0xd358641b48a0204bULL;
};

template<class ContainerAllocator>
struct DataType< ::bebop_simple_test::Altitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bebop_simple_test/Altitude";
  }

  static const char* value(const ::bebop_simple_test::Altitude_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bebop_simple_test::Altitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ardrone3PilotingStateAltitudeChanged\n\
# auto-generated from up stream XML files at\n\
#   github.com/Parrot-Developers/libARCommands/tree/master/Xml\n\
# To check upstream commit hash, refer to last_build_info file\n\
# Do not modify this file by hand. Check scripts/meta folder for generator files.\n\
#\n\
# SDK Comment: Drones altitude changed.\\n The altitude reported is the altitude above the take off point.\\n To get the altitude above sea level, see [PositionChanged](#1-4-4).\n\
\n\
Header header\n\
\n\
# Altitude in meters\n\
float64 altitude\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::bebop_simple_test::Altitude_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bebop_simple_test::Altitude_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Altitude_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bebop_simple_test::Altitude_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bebop_simple_test::Altitude_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEBOP_SIMPLE_TEST_MESSAGE_ALTITUDE_H
